apiVersion: v1
kind: Service
metadata:
  namespace: $ENVIRONMENT_NAME
  name: linton-booking-api-lb
  labels:
    app: linton-booking-api-lb
spec:
  type: LoadBalancer
  selector:
    app: linton-booking-api
  ports:
    - port: 8080
      targetPort: 8080
