apiVersion: v1
kind: Service
metadata:
  namespace: $ENVIRONMENT_NAME
  name: linton-web-lb
  labels:
    app: linton-web-lb
spec:
  type: LoadBalancer
  selector:
    app: linton-web
  ports:
    - port: 8081
      targetPort: 8080

