apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $ENVIRONMENT_NAME
  name: linton-web
  labels:
    app: linton-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linton-web
  template:
    metadata:
      labels:
        app: linton-web
    spec:
      containers:
        - name: linton-web-container
          image: $DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: $ENVIRONMENT_NAME
  name: linton-web
  labels:
    app: linton-web
spec:
  type: NodePort
  selector:
    app: linton-web
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $ENVIRONMENT_NAME
  name: linton-config-map
data:
  application-k8s.yml: |-
    linton:
      environment: $ENVIRONMENT_NAME
